matrix:
- name: Python Source
  pipeline:
    - pyspelling.filters.python
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.py
- name: C++ Source
  pipeline:
    - pyspelling.filters.cpp
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.cpp|code/**/*.hpp
- name: Markdown
  pipeline:
    - pyspelling.filters.markdown
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.md
