matrix:
- name: Python Source
  pipeline:
    - pyspelling.filters.url: 
        urls: true             
        emails: false 
    - pyspelling.filters.python
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.py
- name: Markdown
  pipeline:
    - pyspelling.filters.url: 
        urls: true             
        emails: false 
    - pyspelling.filters.markdown
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.md
- name: C++ Source
  pipeline:
    - pyspelling.filters.url: 
        urls: true             
        emails: false 
    - pyspelling.filters.context:
        context_visible_first: true
        delimiters:
          - open: '\\param\[(?:in|out)\]\s+\w+'
            close: '\s'
    - pyspelling.filters.cpp
  dictionary:
    wordlists:
    - .wordlist.txt
    output: pyspelling.dict
  sources:
  - code/**/*.cpp|code/**/*.hpp
  expect_match: false
