controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    compliant_trajectory_controller:
      type: compliant_trajectory_controller/CompliantTrajectoryController

compliant_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

