##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
    kinematics:
        usd_path: "robot/tx2_60_description/tx2_60.usd"
        usd_robot_root: "/robot"
        isaac_usd_path: ""
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "robot/tx2_60_description/tx2_60.urdf"
        asset_root_path: "robot/tx2_60_description"

        base_link: "base_link"
        ee_link: "ee_link"
        link_names: null
        lock_joints: null
        extra_links: null


        collision_link_names: ['base_link', 'tx2_60_link1', 'tx2_60_link2', 
        'tx2_60_link3', 'tx2_60_link4', ee_link] # List[str]
        collision_spheres:
            base_link:
              - "center": [-0.098, 0.0, 1.0]
                "radius": 0.095
              - "center": [-0.036, 0.064, 1.0]
                "radius": 0.095
              - "center": [-0.03, -0.071, 1.0]
                "radius": 0.095
              - "center": [0.077, 0.0, 1.0]
                "radius": 0.095 
            tx2_60_link1:
              - "center": [0.0, 0.1, 0.185]
                "radius": 0.095
              - "center": [0.0, 0.036, 0.185]
                "radius": 0.095
              - "center": [0.0, -0.0, 0.169]
                "radius": 0.095
              - "center": [0.0, -0.004, 0.128]
                "radius": 0.1
              - "center": [0.0, 0.0, 0.048]
                "radius": 0.1
            tx2_60_link2:
              - "center": [0.02, -0.3, 0.006]
                "radius": 0.06
              - "center": [-0.02, -0.3, 0.006]
                "radius": 0.06
              - "center": [0.04, -0.004, 0.016]
                "radius": 0.06
              - "center": [0.023, -0.251, 0.015]
                "radius": 0.06
              - "center": [0.027, -0.201, 0.018]
                "radius": 0.06
              - "center": [0.034, -0.152, 0.023]
                "radius": 0.06
              - "center": [0.037, -0.103, 0.022]
                "radius": 0.06
              - "center": [0.037, -0.053, 0.018]
                "radius": 0.06
              - "center": [-0.04, -0.004, 0.016]
                "radius": 0.06
              - "center": [-0.023, -0.251, 0.013]
                "radius": 0.06
              - "center": [-0.027, -0.201, 0.014]
                "radius": 0.06
              - "center": [-0.03, -0.152, 0.018]
                "radius": 0.06
              - "center": [-0.033, -0.103, 0.02]
                "radius": 0.06
              - "center": [-0.037, -0.053, 0.021]
                "radius": 0.06
              - "center": [0.028, 0.041, 0.008]
                "radius": 0.06
              - "center": [-0.019, 0.043, 0.011]
                "radius": 0.06
              - "center": [0.002, -0.014, 0.02]
                "radius": 0.06
            tx2_60_link3:
              - "center": [-0.011, 0.063, 0.142]
                "radius": 0.08
              - "center": [-0.009, -0.083, 0.14]
                "radius": 0.07
              - "center": [-0.013, 0.012, 0.141]
                "radius": 0.077
              - "center": [-0.015, -0.036, 0.141]
                "radius": 0.073
              - "center": [0.02, -0.005, 0.14]
                "radius": 0.07
              - "center": [0.003, 0.003, 0.061]
                "radius": 0.09
              - "center": [0.0, -0.061, 0.075]
                "radius": 0.08
            tx2_60_link4:
              - "center": [0.0, 0.02, 0.025]
                "radius": 0.06
              - "center": [0.0, 0.02, 0.18]
                "radius": 0.06
              - "center": [0.0, -0.02, 0.18]
                "radius": 0.06
              - "center": [0.0, -0.02, 0.025]
                "radius": 0.06
              - "center": [0.0, 0.02, 0.077]
                "radius": 0.06
              - "center": [0.0, 0.02, 0.128]
                "radius": 0.06
              - "center": [0.0, -0.02, 0.128]
                "radius": 0.06
              - "center": [0.0, -0.02, 0.077]
                "radius": 0.06
            ee_link:
              - "center": [0.016, 0.03, -0.135]
                "radius": 0.02
              - "center": [-0.016, 0.03, -0.135]
                "radius": 0.02
              - "center": [0.016, 0.03, -0.065]
                "radius": 0.02
              - "center": [-0.016, 0.03, -0.065]
                "radius": 0.02
              - "center": [-0.016, -0.03, -0.065]
                "radius": 0.02
              - "center": [0.016, -0.03, -0.065]
                "radius": 0.02
              - "center": [0.016, -0.03, -0.135]
                "radius": 0.02
              - "center": [-0.016, -0.03, -0.135]
                "radius": 0.02
              - "center": [0.016, 0.0, -0.135]
                "radius": 0.02
              - "center": [-0.016, 0.0, -0.135]
                "radius": 0.02
              - "center": [-0.016, -0.03, -0.088]
                "radius": 0.02
              - "center": [-0.016, -0.03, -0.112]
                "radius": 0.02
              - "center": [0.016, -0.03, -0.088]
                "radius": 0.02
              - "center": [0.016, -0.03, -0.112]
                "radius": 0.02
              - "center": [0.016, 0.03, -0.088]
                "radius": 0.02
              - "center": [0.016, 0.03, -0.112]
                "radius": 0.02
              - "center": [-0.016, 0.03, -0.088]
                "radius": 0.02
              - "center": [-0.016, 0.03, -0.112]
                "radius": 0.02
              - "center": [-0.016, 0.0, -0.065]
                "radius": 0.02
              - "center": [-0.016, 0.0, -0.112]
                "radius": 0.02
              - "center": [-0.016, 0.0, -0.088]
                "radius": 0.02
              - "center": [0.016, -0.0, -0.065]
                "radius": 0.02
              - "center": [0.016, -0.0, -0.088]
                "radius": 0.02
              - "center": [0.016, -0.0, -0.112]
                "radius": 0.02
              - "center": [0.02, -0.03, -0.035]
                "radius": 0.012
              - "center": [0.02, 0.03, -0.035]
                "radius": 0.012
              - "center": [-0.02, -0.03, -0.035]
                "radius": 0.012
              - "center": [-0.02, 0.03, -0.035]
                "radius": 0.012
                   
        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        self_collision_ignore: {
         "base_link": ["tx2_60_link1"],
         "tx2_60_link1": ["tx2_60_link2"],
         "tx2_60_link2": ["tx2_60_link3"],
         "tx2_60_link3": ["tx2_60_link4"],
         "ee_link": ["tx2_60_link4"],
          }
        self_collision_buffer: {
         'base_link': 0,
         'tx2_60_link1': 0,
         'tx2_60_link2': 0,
         'tx2_60_link3': 0,
         'tx2_60_link4': 0,
         'ee_link': 0,
         } # Dict[str, float]

        use_global_cumul: True
        mesh_link_names: ['base_link', 'tx2_60_link1', 'tx2_60_link2', 'tx2_60_link3', 'tx2_60_link4', 'tx2_60_link5', 'tx2_60_link6'] 

        cspace:
          joint_names: ['tx2_60_joint1', 'tx2_60_joint2', 'tx2_60_joint3', 'tx2_60_joint4', 'tx2_60_joint5', 'tx2_60_joint6'] 
          retract_config: [0.000, 0.873, 1.134, 0.000, 1.134, 0.000] # List[float] to check
          null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
          cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
          max_acceleration: 15.0
          max_jerk: 500.0
          

